# Generated by Django 5.2.14 on 2026-05-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="license_number",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="doctors",
        ),
        migrations.AddField(
            model_name="doctor",
            name="patients",
            field=models.ManyToManyField(
                related_name="doctors",
                through="clinic.Appointment",
                to="clinic.patient",
            ),
        ),
    ]
