# Generated by Django 5.2.14 on 2026-05-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0002_remove_doctor_license_number_remove_patient_doctors_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ctscan",
            options={"ordering": ["-scan_date"]},
        ),
        migrations.AddField(
            model_name="ctscan",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="ct_scan/"),
            preserve_default=False,
        ),
    ]
