# Generated by Django 5.2.14 on 2026-05-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0003_alter_ctscan_options_ctscan_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ctscan",
            options={
                "ordering": ["-scan_date"],
                "verbose_name": "CT Scan",
                "verbose_name_plural": "CT Scans",
            },
        ),
    ]
