# Generated by Django 5.2.14 on 2026-05-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0004_alter_ctscan_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                fields=("doctor", "appointment_date"), name="unique_appointment"
            ),
        ),
    ]
