# Generated by Django 5.2.14 on 2026-05-29 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0005_appointment_unique_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="diagnosis",
            field=models.TextField(default="-", max_length=255),
        ),
        migrations.AlterField(
            model_name="patient",
            name="first_name",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name can contain only letters, apostrophes and hyphens.",
                        regex="^[A-Za-zА-Яа-яІіЇїЄє'-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="last_name",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name can contain only letters, apostrophes and hyphens.",
                        regex="^[A-Za-zА-Яа-яІіЇїЄє'-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in format +380XXXXXXXXX",
                        regex="^\\+380\\d{9}$",
                    )
                ],
            ),
        ),
    ]
