# Generated by Django 5.2.14 on 2026-05-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0006_patient_diagnosis_alter_patient_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={"ordering": ["birth_date"]},
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="years_of_experience",
        ),
        migrations.AddField(
            model_name="doctor",
            name="hire_date",
            field=models.DateField(default="2000-01-01"),
        ),
    ]
