# Generated by Django 5.2.14 on 2026-05-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0007_alter_patient_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="hire_date",
            field=models.DateField(),
        ),
    ]
